@startuml
'https://plantuml.com/class-diagram

class Solution44 {
}

class JsonInput {

}

class Object {
    + name : String
    + price : double
    + quantity : int
}

Solution44 o--> JsonInput
JsonInput o--> Object

@enduml